[env]
GOPATH = "{{env.HOME}}/.local/share/go"
_.path = [
  "{{env.HOME}}/.local/bin",
  "{{env.XDG_DATA_HOME | default(value=env.HOME ~ '/.local/share')}}/nvim/mason/bin",
]

[settings]
idiomatic_version_file_enable_tools = ["dotnet"]

[settings.dotnet]
cli_telemetry_optout = true
